# esure-config
---
spring:
  profiles: dev

#
# This is loaded into a list of AggregatorConfiguation objects in the client.
# It is used to determine what action to take when an existing policy is found
# for the same vehicle registration number that is in renewal.
#
quote-suppression-config:
  aggregatorConfigurations:
    - aggregator: GOCOMPARE
      productType: MOTOR
      suppress: SUPPRESS_SAME
    - aggregator: GOCOMPARE
      productType: HOME
      suppress: SUPPRESS_SAME
    - aggregator: CTM
      productType: MOTOR
      suppress: SUPPRESS_SAME
    - aggregator: CTM
      productType: HOME
      suppress: SUPPRESS_SAME
    - aggregator: MSM
      productType: MOTOR
      suppress: SUPPRESS_SAME
    - aggregator: MSM
      productType: HOME
      suppress: SUPPRESS_SAME
    - aggregator: CONFUSED
      productType: MOTOR
      suppress: SUPPRESS_SAME
    - aggregator: CONFUSED
      productType: HOME
      suppress: SUPPRESS_SAME

test.message: test
#
# This is used to map short product codes (such as those received from
# aggregators) to a product type. This is loaded into a map on the client.
#
product-types-config:
  productTypeMap:
    EM: MOTOR
    FC: MOTOR
    SW: MOTOR
    EH: HOME
    SH: HOME
 